name: pre-release

on:
  pull_request:
    branches:
      - master

jobs:
  pre-release:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 2

    - run: |
        git fetch
        git checkout develop

    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 11

    - name: Run tests
      run: mvn -B test --file pom.xml

    - name: Get latest release version
      run: |
        curl -X GET \
          https://api.github.com/repos/whelk-io/spring-boot-starter-data-logging/releases/latest \
          -o /tmp/release.json
    - name: Increment version in pom.xml
      run: |
        old_version=`cat /tmp/release.json | grep tag_name -m 1 | awk '{$1=$1};1' | awk -F':' '{print $2}' | awk -F'"' '{print $2}'` \
        && echo "Old version: " $old_version \
        && major_version=`echo $old_version | awk -F'-' '{print $1}' | awk -F'.' '{print $1}'` \
        && minor_version=`echo $old_version | awk -F'-' '{print $1}' | awk -F'.' '{print $2}'` \
        && patch_version=`echo $old_version | awk -F'-' '{print $1}' | awk -F'.' '{print $3}'` \
        && let "patch_version+=1" \
        && new_version=$major_version"."$minor_version"."$patch_version"-RELEASE" \
        && echo "New version: " $new_version \
        && mvn -B versions:set -DnewVersion=$new_version --file pom.xml
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.BUILD_EMAIL }}
        git config --local user.name ${{ secrets.BUILD_USERNAME }}
        [[ `git diff` ]] && git commit -m "Update version in pom.xml" -a || echo "ignore commit, no changes"
        git push

